### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by kborchers** [jquery-support/react-globalize#1]

**Comment by kborchers** [comment]
@rxaviers @alunny FYI, I am starting to work on this in the evenings when I have free time. That free time is rare but trying to make time to write a bit of JS here and there and keep up on current tools. :smile: I would like to implement #34 as well but felt like tests would be nice to have before making a change like that but if either of you feel comfortable making that change and can test in apps you have before tests are available here, please do so.

**Comment by rxaviers** [comment]
Tests are very welcome and urgent here, so that's very good to know. About #34, I will give a reply soon.
