### ISSUE TITLE
Allow to pass options as props

### ISSUE THREAD

**Issue by fdecampredon** [jquery-support/react-globalize#35]
```javascript
<FormatDate options={{time: short}} />
```
Is also a bit weird, also for performance point of view (even if it's really slight) it forces creation of a lot of object.

Something like: 
```javascript
<FormatDate time="short" />
```

Could be more 'react' like

**Comment by rxaviers** [comment]
This is tricker for methods that `options` is not the only argument. For example, `<FormatCurrency/>`.

**Comment by fdecampredon** [comment]
From what I see on globalize documentation there is no really name collision so is it really a problem ?

**Comment by rxaviers** [comment]
Not that it's a problem, but managing this flatten mapping is going to require a bigger maintenance effort over time. FWIW, I like how the shorter version looks like, but I'm afraid of the maintenance.

@kborchers @alunny any input?

**Comment by kborchers** [comment]
I agree with @rxaviers. This would become very cumbersome to maintain if we added every option for every Globalize function as props on a component.

**Comment by kborchers** [comment]
I think we agree here that this would hinder maintenance but @rxaviers or @alunny please reopen if you have changed your mind.
