### ISSUE TITLE
React 15.x

### ISSUE THREAD

**Issue by rxaviers** [jquery-support/react-globalize#55]
React supersedes `0.14` with `15.0` (major update), so we need to updated our peer dependency range accordingly and make sure there's no breaking changes.

> As a reminder, we’re switching to major versions to indicate that we have been using React in production for a long time. This 15.0 release follows our previous 0.14 version and we’ll continue to follow semver like we’ve been doing since 2013

https://facebook.github.io/react/blog/2016/04/07/react-v15.html

**Comment by rxaviers** [comment]
PR #56 updates react range to include React `15.x`. I confirmed tests pass plus it didn't break an application I have. Potentially, this is all we need to close the issue, but I'm still unsure if we need any changes about [SPAN](https://github.com/jquery-support/react-globalize/blob/master/src/generator.js#L35) usage by formatters.

**Comment by necolas** [comment]
I think this issue can be closed

**Comment by rxaviers** [comment]
Yeap, it seems so. Thanks

PS: For some reason I had used `Ref #55` in the commit message instead of `Closed`, but looking at it now it seems like it's addressed.
