### ISSUE TITLE
Don't forward all props to underlying dom component

### ISSUE THREAD

**Issue by necolas** [jquery-support/react-globalize#57]
This causes warnings in React >=15.2.0 because non-html attributes are being passed to the dom component

**Comment by rxaviers** [comment]
Originally, this has been added to allow `className` or `style` to be propagated. We can either whitelist the props we want to be passed (e.g., the ones cited) or blacklist the ones we don't (e.g,. `ref`).

Opinions?

**Comment by necolas** [comment]
You can still spread the unknown props, but shouldn't forward the composite component's props - `elements`, `variables` – to the underlying DOM component.

**Comment by rxaviers** [comment]
Ok. I understood now what you're saying. A solution is sketched here https://github.com/jquery-support/react-globalize/pull/58.
